### PR TITLE
treat properties that consist of an allOf array containing a single enum as enums

### LINKED ISSUE #48: static enum extension methods are (sometimes?) wrongly referenced
This is something that has tripped me up myself once:
https://github.com/dart-lang/sdk/issues/44620

when defing extensions with static methods, those methods don't become available as members on the class that they're extending, but can be called directly on the extension class.

This seems to be a problem when the schema defines a model that contains an enum via allOf. Here's an example (highlighting the errors):

<details>
<summary>dart file generatd from wrapping type</summary>

```dart
       part of openapi.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.

// PatchedPpeEditRequest
class PatchedPpeEditRequest {
    
      String? name;
    
      CategoryEnum? category;
    
      String? use;
    
      ApiResponse? datasheet;
PatchedPpeEditRequest({ this.name,
    this.category,
    this.use,
    this.datasheet,
     });

  @override
  String toString() {
    return 'PatchedPpeEditRequest[name=$name, category=$category, use=$use, datasheet=$datasheet, ]';
  }

  fromJson(Map<String, dynamic>? json) {
    if (json == null) return;
  


        name = (json[r'name'] == null) ? null : (json[r'name'] as String?);

      

        category = (json[r'category'] == null) ? null : CategoryEnum.fromJson(json[r'category']);
//______________________________________________________________ERROR^^^^^^^
      

        use = (json[r'use'] == null) ? null : (json[r'use'] as String?);

      

        datasheet = (json[r'datasheet'] == null) ? null : 
//___________________________________(different ERROR) ^^^^
      
  }

  PatchedPpeEditRequest.fromJson(Map<String, dynamic>? json) {
    fromJson(json); // allows child classes to call
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
  if (name != null) {
          json[r'name'] = name;
    } 
  if (category != null) {
          json[r'category'] = category?.toJson();
    } 
  if (use != null) {
          json[r'use'] = use;
    } 
  if (datasheet != null) {
    } 
    return json;
  }
  static List<PatchedPpeEditRequest> listFromJson(List<dynamic>? json) {
    return json == null ? <PatchedPpeEditRequest>[] : json.map((value) => PatchedPpeEditRequest.fromJson(value)).toList();
  }

  static Map<String, PatchedPpeEditRequest> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, PatchedPpeEditRequest>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) => map[key] = PatchedPpeEditRequest.fromJson(value));
    }
    return map;
  }

  @override
  bool operator ==(Object? __other) {
    if (identical(this, __other)) {
      return true;
    }

    if (__other is PatchedPpeEditRequest && runtimeType == __other.runtimeType) {
    return 

     name == __other.name &&
  
          category == __other.category && // __other
    

     use == __other.use &&
  
          datasheet == __other.datasheet    
    ;
    }

    return false;
  }

  @override
  int get hashCode {
    var hashCode = runtimeType.hashCode;

    
          if (name != null) {
        hashCode = hashCode * 31 + name.hashCode;
            }

    
          if (category != null) {
        hashCode = hashCode * 31 + category.hashCode;
            }

    
          if (use != null) {
        hashCode = hashCode * 31 + use.hashCode;
            }

    
          if (datasheet != null) {
        hashCode = hashCode * 31 + datasheet.hashCode;
            }

    

    return hashCode;
  }

  PatchedPpeEditRequest copyWith({
         String? name,
         CategoryEnum? category,
         String? use,
         ApiResponse? datasheet,
    }) {

  name ??= this.name;
  category ??= this.category;
  use ??= this.use;
  datasheet ??= this.datasheet;
  
      final _copy_name = name;
        final _copy_category = category?.copyWith();
        //__________________________ERROR^^^^^^^^^
        final _copy_use = use;
        final _copy_datasheet = datasheet;
  

    return PatchedPpeEditRequest(
      name: _copy_name,category: _copy_category,use: _copy_use,datasheet: _copy_datasheet,);
  }
}
```

</details>
The error messages from dart analyzer :

<details>
<summary>errors</summary>

```
 error • lib/model/patched_ppe_edit_request.dart:36:70 • The method 'fromJson' isn't defined for the type 'CategoryEnum'. Try correcting the name to the name of an existing method, or defining a method named 'fromJson'. •              
          undefined_method                                                                                                                                                                                                                  
  error • lib/model/patched_ppe_edit_request.dart:47:3 • Expected an identifier. • missing_identifier                                                                                                                                       
  error • lib/model/patched_ppe_edit_request.dart:47:3 • Expected to find ';'. • expected_token                                                                                                                                             
  error • lib/model/patched_ppe_edit_request.dart:145:42 • Static method 'copyWith' can't be accessed through an instance. Try using the class 'CategoryEnumExtension' to access the method. •                                              
          instance_access_to_static_member                                                                                                                                                                                                  
  error • lib/model/patched_ppe_edit_request.dart:145:50 • 1 positional argument(s) expected, but 0 found. Try adding the missing arguments. • not_enough_positional_arguments
```
</details>

This issue is about two of these errors, the calls to fromJson and copyWith. Both of them would need to be called like this instead to be valied code:
```
CategoryEnumExtension.fromJson(...)
CategoryEnumExtension.copyWith(...)
```
In the case of the copywith method, assuming I understand the intention behind it, I think that one should actually rather be non-static and defined something like this to work as it looks to be intended to be used here:
```dart
CategoryEnum copyWith() => this;
```
but then, in the case of enums it seems pointless really to have such a method if not for the sake of having a consistent api.

You'll notice that there are additional errors, I will sift through the rest gradually :p
Here's the contents of the file defining the method:
<details>
<summary>generated enum code</summary>

```dart
part of openapi.api;

// This file is generated by https://github.com/dart-ogurets/dart-openapi-maven - you should not modify it
// log generation bugs on Github, as part of the license, you must not remove these headers from the Mustache templates.


enum CategoryEnum {
    gloves, clothes, shoes, mask
}

extension CategoryEnumExtension on CategoryEnum {
  String? get name => toMap[this];

  // you have to call this extension class to use this as this is not yet supported
  static CategoryEnum? type(String name) => fromMap[name];

  static Map<String, CategoryEnum> fromMap = {  
  'Gloves':CategoryEnum.gloves, 'Clothes':CategoryEnum.clothes, 'Shoes':CategoryEnum.shoes, 'mask':CategoryEnum.mask
 };
  static Map<CategoryEnum, String> toMap = {  
  CategoryEnum.gloves:'Gloves', CategoryEnum.clothes:'Clothes', CategoryEnum.shoes:'Shoes', CategoryEnum.mask:'mask'
 };

  static CategoryEnum? fromJson(dynamic data) => data == null ? null : fromMap[data];

  dynamic toJson() => toMap[this];

  static List<CategoryEnum> listFromJson(List<dynamic>? json) =>
    json == null ? <CategoryEnum>[] : json.map((value) => fromJson(value)).toList().fromNull();

  static CategoryEnum copyWith(CategoryEnum instance) => instance;

  static Map<String, CategoryEnum> mapFromJson(Map<String, dynamic>? json) {
    final map = <String, CategoryEnum>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) {
        final val = fromJson(value);
        if (val != null) {
          map[key] = val;
        }
      });
    }
    return map;
  }
}
```
</details>
The part of the schema that defines the enum and the model that contains it:
<details>
<summary>schema</summary>

```yaml
components:
  schemas:
    CategoryEnum:
      enum:
      - Gloves
      - Clothes
      - Shoes
      - mask
      type: string
    PatchedPpeEditRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
        category:
          allOf:
          - $ref: '#/components/schemas/CategoryEnum'
          nullable: true
        use:
          type: string
        datasheet:
          type: string
          format: binary
          nullable: true

```
</details>

### PR DESCRIPTION
**Pull request by NANASHI0X74**
fixes #48, in the way I discussed over there.

### CODE REVIEW

**Comment by NANASHI0X74** [comment]
🤔 hmm I thought I'd made sure the tests go through. I'll have another look at it later

**Comment by NANASHI0X74** [comment]
just forgot to stage some changes 😄

File: src/main/java/cd/connect/openapi/DartV3ApiGenerator.java [hunk 1]
```diff
@@ -217,8 +224,46 @@ private void correctInternals(CodegenModel model, CodegenProperty cp, boolean cl
...
+                if (referencedEnum != null && !referencedEnum.isEmpty()) {
+                  isComposedEnum = true;
+                  cp.isModel = false;
+                }
+              }
+            }
+          }
+        }
+      } catch (Exception e) {
+        e.printStackTrace();
```
Comment (rvowles) [inline src/main/java/cd/connect/openapi/DartV3ApiGenerator.java]: this needs to be getLog().error("....", e)

Comment (NANASHI0X74) [reply src/main/java/cd/connect/openapi/DartV3ApiGenerator.java]: ah... I had that there for debugging purposes and didn't really intend to log anything there in the end, but just assume that the schema isn't of the form described and silently continue as normal. But now that I'm catching most errors that could come up anyway with the if statements it may make sense to log something there

Comment (NANASHI0X74) [reply src/main/java/cd/connect/openapi/DartV3ApiGenerator.java]: alright, how about this?
